import { useMemo, useState } from 'react';
import { ArrowRight, Bike, CalendarDays, Check, Clock3, MapPin, MessageCircle, Minus, Phone, Plus, Search, ShoppingBag, Sparkles, X } from 'lucide-react';

type Category = 'All' | 'Shawarma' | 'Pizza' | 'Burger' | 'Fish' | 'Pastries' | 'Snacks';
type Product = { id:number; name:string; category:Exclude<Category,'All'>; price:number; priceLabel:string; desc:string; emoji:string; featured?:boolean };
const WHATSAPP='2349166685298';
const products:Product[]=[
{id:1,name:'Beef Shawarma',category:'Shawarma',price:3500,priceLabel:'₦3,500',desc:'Tender beef, fresh vegetables and signature sauce, wrapped fresh.',emoji:'🌯',featured:true},
{id:2,name:'Chicken Shawarma',category:'Shawarma',price:4000,priceLabel:'₦4,000',desc:'Juicy chicken, crisp vegetables and creamy house sauce.',emoji:'🌯',featured:true},
{id:3,name:'Special Shawarma',category:'Shawarma',price:7000,priceLabel:'₦7,000',desc:'A loaded special wrap for serious shawarma cravings.',emoji:'🌯'},
{id:4,name:'Jumbo Shawarma',category:'Shawarma',price:6000,priceLabel:'₦6,000',desc:'Extra-large, extra-loaded and made to satisfy.',emoji:'🌯'},
{id:5,name:'Mix Grill Shawarma',category:'Shawarma',price:5000,priceLabel:'₦5,000',desc:'A rich mix of grilled flavours in one satisfying wrap.',emoji:'🌯'},
{id:6,name:'Chicken Pizza',category:'Pizza',price:7000,priceLabel:'₦7,000–₦15,000',desc:'Small ₦7k · Medium ₦9k · Large ₦12k · Extra Large ₦15k.',emoji:'🍕',featured:true},
{id:7,name:'Beef Pizza',category:'Pizza',price:6500,priceLabel:'₦6,500–₦13,000',desc:'Small ₦6.5k · Medium ₦8k · Large ₦11k · Extra Large ₦13k.',emoji:'🍕'},
{id:8,name:'Goat Meat Pizza',category:'Pizza',price:7000,priceLabel:'₦7,000–₦15,000',desc:'Small ₦7k · Medium ₦9.5k · Large ₦13k · Extra Large ₦15k.',emoji:'🍕'},
{id:9,name:'Special Pizza',category:'Pizza',price:7000,priceLabel:'₦7,000–₦16,000',desc:'Small ₦7k · Medium ₦9.5k · Large ₦13k · Extra Large ₦16k.',emoji:'🍕'},
{id:10,name:'4 in 1 Pizza',category:'Pizza',price:16000,priceLabel:'₦16,000',desc:'Four flavours in one pizza — perfect for sharing.',emoji:'🍕',featured:true},
{id:11,name:'Half & Half Pizza',category:'Pizza',price:8000,priceLabel:'₦8,000–₦18,000',desc:'Small ₦8k · Medium ₦9k · Large ₦12k · Extra Large ₦18k.',emoji:'🍕'},
{id:12,name:'One Decker Burger',category:'Burger',price:0,priceLabel:'Price on request',desc:'Classic juicy burger with fresh toppings.',emoji:'🍔'},
{id:13,name:'Two Decker Burger',category:'Burger',price:0,priceLabel:'Price on request',desc:'Double the layers, double the satisfaction.',emoji:'🍔'},
{id:14,name:'Three Decker Burger',category:'Burger',price:0,priceLabel:'Price on request',desc:'The big one for serious hunger.',emoji:'🍔'},
{id:15,name:'Barbecue Fish — Small',category:'Fish',price:13000,priceLabel:'₦13,000',desc:'Smoky, seasoned and grilled fresh.',emoji:'🐟',featured:true},
{id:16,name:'Barbecue Fish — Medium',category:'Fish',price:15000,priceLabel:'₦15,000',desc:'A generous grilled fish portion for a proper meal.',emoji:'🐟'},
{id:17,name:'Barbecue Fish — Large',category:'Fish',price:17000,priceLabel:'₦17,000',desc:'Bigger portion, bold seasoning and smoky finish.',emoji:'🐟'},
{id:18,name:'Barbecue Fish — Extra Large',category:'Fish',price:20000,priceLabel:'₦20,000',desc:'The full-size option for sharing and big appetites.',emoji:'🐟'},
{id:19,name:'Meat Pie',category:'Pastries',price:0,priceLabel:'Price on request',desc:'Golden pastry filled with savoury meat.',emoji:'🥧'},
{id:20,name:'Buns',category:'Pastries',price:500,priceLabel:'₦500 each',desc:'Soft, freshly prepared golden buns.',emoji:'🍞'},
{id:21,name:'Egg Roll',category:'Pastries',price:0,priceLabel:'Price on request',desc:'Crispy golden coating with a whole egg inside.',emoji:'🥚'},
{id:22,name:'Puff Puff',category:'Pastries',price:0,priceLabel:'Price on request',desc:'Fresh, fluffy and lightly sweet.',emoji:'🍩'},
{id:23,name:'Peanut',category:'Snacks',price:0,priceLabel:'Price on request',desc:'Crunchy, snackable and perfect for sharing.',emoji:'🥜'},
{id:24,name:'Popcorn',category:'Snacks',price:500,priceLabel:'₦500–₦1,000',desc:'Fresh popcorn for cravings, parties and events.',emoji:'🍿',featured:true}
];
const imageForCategory:Record<Exclude<Category,'All'>,string>={
Shawarma:'https://images.pexels.com/photos/5779377/pexels-photo-5779377.jpeg?auto=compress&cs=tinysrgb&w=900',Pizza:'https://images.pexels.com/photos/2619967/pexels-photo-2619967.jpeg?auto=compress&cs=tinysrgb&w=900',Burger:'https://images.pexels.com/photos/1938272/pexels-photo-1938272.jpeg?auto=compress&cs=tinysrgb&w=900',Fish:'https://images.pexels.com/photos/2233733/pexels-photo-2233733.jpeg?auto=compress&cs=tinysrgb&w=900',Pastries:'https://images.pexels.com/photos/35185917/pexels-photo-35185917.jpeg?auto=compress&cs=tinysrgb&w=900',Snacks:'https://images.pexels.com/photos/12937021/pexels-photo-12937021.jpeg?auto=compress&cs=tinysrgb&w=900'};

export default function App(){
const [category,setCategory]=useState<Category>('All');const [search,setSearch]=useState('');const [cart,setCart]=useState<Record<number,number>>({});const [cartOpen,setCartOpen]=useState(false);const [bookingOpen,setBookingOpen]=useState(false);const [mobileNav,setMobileNav]=useState(false);
const visible=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&p.name.toLowerCase().includes(search.toLowerCase())),[category,search]);const cartItems=products.filter(p=>cart[p.id]);const count=Object.values(cart).reduce((a,b)=>a+b,0);const add=(id:number)=>setCart(c=>({...c,[id]:(c[id]||0)+1}));const remove=(id:number)=>setCart(c=>{const n={...c};if((n[id]||0)<=1)delete n[id];else n[id]--;return n});
const orderText=cartItems.length?`Hello De Wizzy Shawarma! I'd like to order:\n${cartItems.map(p=>`• ${p.name} x${cart[p.id]} — ${p.priceLabel}`).join('\n')}\n\nPlease confirm availability, options and final total.`:'Hello De Wizzy Shawarma! I would like to place an order. Please assist me.';const wa=`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(orderText)}`;
return <div className="site"><div className="topline"><span>Port Harcourt's home of fresh cravings</span><span><Clock3 size={13}/> Open for pickup & WhatsApp orders</span></div><header className="nav"><a className="brand" href="#home"><img className="brandLogo" src="./resources/de-wizzy-logo.jpeg" alt="De Wizzy Shawarma logo"/><span><b>DE WIZZY</b><small>SHAWARMA & MORE</small></span></a><nav className={mobileNav?'open':''}><a href="#menu" onClick={()=>setMobileNav(false)}>Menu</a><a href="#services" onClick={()=>setMobileNav(false)}>Events</a><a href="#about" onClick={()=>setMobileNav(false)}>Our story</a><a href="#contact" onClick={()=>setMobileNav(false)}>Contact</a></nav><div className="navActions"><a className="navWhats" href={wa} target="_blank" rel="noreferrer"><MessageCircle size={16}/> WhatsApp</a><button className="cartBtn" onClick={()=>setCartOpen(true)}><ShoppingBag size={18}/><span>Cart</span>{count>0&&<i>{count}</i>}</button><button className="hamb" onClick={()=>setMobileNav(v=>!v)}>{mobileNav?<X/>:<span>☰</span>}</button></div></header>
<main><section id="home" className="hero"><div className="heroCopy"><div className="eyebrow"><Sparkles size={14}/> DE WIZZY SHAWARMA</div><h1>Good food.<br/><em>Great moments.</em></h1><p>Fresh shawarma, loaded pizza, grilled fish, burgers, snacks and event treats — made for Port Harcourt cravings.</p><div className="heroActions"><a href="#menu" className="primary">Explore the menu <ArrowRight size={17}/></a><a href={wa} target="_blank" rel="noreferrer" className="whatsapp"><MessageCircle size={17}/> Order on WhatsApp</a></div><div className="heroTrust"><span><Check/> Freshly prepared</span><span><Check/> Pickup available</span><span><Check/> Events & parties</span></div></div><div className="heroVisual"><div className="imageFrame"><img src="./resources/de-wizzy-flyer.jpg" alt="De Wizzy Shawarma"/></div><div className="floatingReview"><div className="stars">★★★★★</div><b>Taste you never forget.</b><small>De Wizzy Shawarma · Port Harcourt</small></div></div></section>
<section className="featureBar"><div><b>Made fresh</b><small>Every order, every time</small></div><div><b>Pickup now</b><small>Delivery expanding soon</small></div><div><b>Event catering</b><small>Birthday · Wedding · School</small></div><div><b>Port Harcourt</b><small>Rumuosi & surrounding areas</small></div></section>
<section id="menu" className="menuSection"><div className="sectionIntro"><div><p className="eyebrow">THE DE WIZZY MENU</p><h2>Pick your <em>favourite.</em></h2><p>From a quick bite to a full event spread, there's something for every appetite.</p><small className="imageNote">Food images are professional stock photos for presentation; actual menu items may vary.</small></div><button className="outlineBtn" onClick={()=>setBookingOpen(true)}>Book an event <ArrowRight size={16}/></button></div><div className="menuTools"><div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search shawarma, pizza, fish..."/></div><div className="tabs">{(['All','Shawarma','Pizza','Burger','Fish','Pastries','Snacks'] as Category[]).map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div></div><div className="grid">{visible.map(p=><article className={'card '+(p.featured?'featured':'')} key={p.id}><div className="foodArt"><img src={imageForCategory[p.category]} alt={p.name} loading="lazy"/><label>{p.category}</label>{p.featured&&<b className="popular">Popular</b>}</div><div className="cardBody"><h3>{p.name}</h3><p>{p.desc}</p><div className="cardFoot"><div><strong>{p.priceLabel}</strong></div><button onClick={()=>add(p.id)}><Plus size={15}/> Add</button></div></div></article>)}</div></section>
<section id="services" className="services"><div className="serviceCopy"><p className="eyebrow">EVENTS & CATERING</p><h2>Make your next event <em>taste better.</em></h2><p>Planning a birthday, wedding, school programme or private gathering? Bring De Wizzy along.</p><button className="primary" onClick={()=>setBookingOpen(true)}>Book De Wizzy <ArrowRight size={17}/></button></div><div className="serviceGrid"><div className="serviceCard"><span>01</span><h3>Birthday parties</h3><p>Party food, popcorn and custom orders.</p></div><div className="serviceCard"><span>02</span><h3>Weddings</h3><p>Food service that keeps guests satisfied.</p></div><div className="serviceCard"><span>03</span><h3>School events</h3><p>Bulk treats and easy ordering.</p></div><div className="serviceCard"><span>04</span><h3>Custom events</h3><p>Indoor and outdoor services.</p></div></div></section>
<section id="about" className="about"><div className="aboutVisual"><img src="./resources/de-wizzy-menu.jpg" alt="De Wizzy menu"/></div><div className="aboutCopy"><p className="eyebrow">WHY DE WIZZY</p><h2>Street-food energy.<br/><em>Premium experience.</em></h2><p>De Wizzy Shawarma is building a food experience around flavour, convenience and memorable service — from the first click to the last bite.</p><div className="stats"><div><b>24+</b><small>Menu choices</small></div><div><b>PH</b><small>Port Harcourt</small></div><div><b>WA</b><small>Fast ordering</small></div></div></div></section>
<section className="cta"><div><p className="eyebrow">YOUR NEXT CRAVING</p><h2>Don't just think about it.<br/><em>Order it.</em></h2></div><a href={wa} target="_blank" rel="noreferrer" className="whatsapp big"><MessageCircle/> Start a WhatsApp order <ArrowRight/></a></section><section id="contact" className="contact"><div><p className="eyebrow">CONTACT DE WIZZY</p><h2>Let's make it <em>happen.</em></h2><p>For orders, pickup enquiries and event bookings, reach us directly.</p></div><div className="contactInfo"><a href={wa} target="_blank" rel="noreferrer"><MessageCircle/><span><small>WhatsApp</small><b>0916 668 5298</b></span><ArrowRight/></a><a href="tel:+2349166685298"><Phone/><span><small>Call us</small><b>+234 916 668 5298</b></span><ArrowRight/></a><div><MapPin/><span><small>Location</small><b>Rumuosi, Port Harcourt</b></span></div></div></section></main>
<footer><div className="footerBrand"><div className="brand"><img className="brandLogo" src="./resources/de-wizzy-logo.jpeg" alt="De Wizzy Shawarma logo"/><span><b>DE WIZZY</b><small>SHAWARMA & MORE</small></span></div><p>Taste you never forget.</p></div><div className="footerLinks"><a href="#menu">Menu</a><a href="#services">Events</a><a href="#contact">Contact</a><a href={wa} target="_blank" rel="noreferrer">WhatsApp</a></div><small>© 2026 De Wizzy Shawarma · Port Harcourt</small></footer>
{cartOpen&&<div className="overlay" onClick={()=>setCartOpen(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawerHead"><div><p className="eyebrow">YOUR ORDER</p><h2>Ready when you are.</h2></div><button onClick={()=>setCartOpen(false)}><X/></button></div>{cartItems.length===0?<div className="empty"><ShoppingBag size={42}/><h3>Your cart is waiting.</h3><p>Add your favourites and send the order straight to WhatsApp.</p><button className="primary" onClick={()=>setCartOpen(false)}>Browse menu</button></div>:<><div className="cartList">{cartItems.map(p=><div className="cartRow" key={p.id}><span className="mini">{p.emoji}</span><div><b>{p.name}</b><small>{p.priceLabel}</small></div><div className="qty"><button onClick={()=>remove(p.id)}><Minus size={13}/></button><span>{cart[p.id]}</span><button onClick={()=>add(p.id)}><Plus size={13}/></button></div></div>)}</div><div className="cartNote">Some menu items have options or prices still being confirmed. De Wizzy will confirm your final total on WhatsApp.</div><a className="whatsapp big checkout" href={wa} target="_blank" rel="noreferrer"><MessageCircle/> Send order to WhatsApp</a></>}</aside></div>}
{bookingOpen&&<div className="modalWrap" onClick={()=>setBookingOpen(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="modalClose" onClick={()=>setBookingOpen(false)}><X/></button><p className="eyebrow">EVENT BOOKING</p><h2>Let's plan something <em>special.</em></h2><p>Share the basics and we'll continue with you on WhatsApp.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const text=`Hello De Wizzy Shawarma! I'd like to book you for an event.\n\nEvent: ${f.get('event')}\nDate: ${f.get('date')}\nGuests: ${f.get('guests')}\nLocation: ${f.get('location')}\nDetails: ${f.get('details')}`;window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(text)}`,'_blank')}}><input name="event" required placeholder="Event type"/><input name="date" type="date" required/><input name="guests" type="number" min="1" required placeholder="Number of guests"/><input name="location" required placeholder="Event location in Port Harcourt"/><textarea name="details" rows={4} placeholder="What would you like us to provide?"/><button className="primary" type="submit">Continue on WhatsApp <MessageCircle size={17}/></button></form></div></div>}</div>;
}
